### ISSUE TITLE
Doesn't work on the side bar

### ISSUE THREAD

**Issue by vl-vincent** [nikeee/visual-studio-dark#10]
Hi,

It's a great theme but it doesn't work on the side bar. After restarting Sublime Text 3, I have the default side bar.

![image](https://cloud.githubusercontent.com/assets/28391312/25985799/d90ac720-36ec-11e7-9f4a-106ae06551af.png)

**Comment by nikeee** [comment]
IIRC, the side bar is not affected by `tmTheme`s by design. I think you need a `sublime-theme` for that. This repos just contains a color scheme for syntax highlighting.
