### ISSUE TITLE
Side Bar Color not changed

### ISSUE THREAD

**Issue by faisal95bd** [nikeee/visual-studio-dark#15]

**Comment by nikeee** [comment]
Whats missing?

**Comment by faisal95bd** [comment]
The side bar theme.

**Comment by nikeee** [comment]
If I'm not mistaking, the side bar cannot be changed using a tmTheme.

You can, however, change the background color of the side bar to adapt to the rest of the coloring:
https://stackoverflow.com/a/46463891

**Comment by faisal95bd** [comment]
Oh! i didn’t know that.
Im not much a theme/graphics guy. Always like to use the default ones.  But i tried to use something new today.
Anyway, you did a good job. Thanks for your time. :)
