### ISSUE TITLE
No theme

### ISSUE THREAD

**Issue by paulyn000** [nikeee/visual-studio-dark#8]
Please create a theme to change the sidebar brackground color same as the body. Sorry for posting this as an issue. thanks btw.

**Comment by nikeee** [comment]
Once upon a time, I actually had one. It was terrible, so I never released it.
Maybe you can evaluate this one:
http://srff.deviantart.com/art/Visual-Studio-2013-for-Sublime-Text-396364965
IIRC there was another one, but I cant find it right now.

**Comment by paulyn000** [comment]
i've already seen this one. I like your style and colors compared to this.
